### ISSUE TITLE
Out of memory when training with a P-100, 12G

### ISSUE THREAD

**Issue by muyoucun** [sirius-ai/MobileFaceNet_TF#5]
sorry but I met with the OOM problem when training with 128 batch_size and  12G P-100.
is that normal? 
i wonder why this happened since my card is 12G memory and i just want use larger batch_size.
thanks.

**Comment by xsr-ai** [comment]
how many classes are there in your datasets? maybe you should minimize the batchsize.

**Comment by ltcs11** [comment]
since i also met with the OOM problem with 90 batch_size(default)
my device has 8G memory

finally i choose 64 batch_size to finish the training, it takes about 7G memory
so apparently the OOM problem will occur when deal with 128 batch_size using 12G memory GPU

you can use "nvidia-smi" to check your GPU status, including memory usage

**Comment by sirius-ai** [comment]
thanks Itcs11.
close, when need reopen.
